version: "3.6"

services:
    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest

    pg-docker:
        image: postgres:14-alpine
        container_name: dev-postgresql
        environment:
            POSTGRES_DB: meudb
            POSTGRES_PASSWORD: 1234567
        ports:
            - 5432:5432
        volumes:
            - ./data/postgresql/data:/var/lib/postgresql/data
        networks:
            - dev-network

    pgadmin-docker:
        image: dpage/pgadmin4
        container_name: dev-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: post@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234567
        ports:
            - 5050:80
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin
        depends_on:
            - pg-docker
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge

